{"uuid":"60b08778-2e02-4d17-879d-188ea8d63b53","name":"Default Suite","children":["404ffc12-3cfe-4660-94a2-f5c470227c58"],"befores":[{"name":"startServer","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.ExceptionInInitializerError","trace":"java.lang.ExceptionInInitializerError\n\tat testBase.TestBase.startServer(TestBase.java:21)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:345)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\n\tat org.testng.TestNG.run(TestNG.java:1000)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\nCaused by: java.lang.RuntimeException: java.net.ConnectException: Connection refused (Connection refused)\n\tat org.example.factory.AppiumDriverFactory.getDevices(AppiumDriverFactory.java:59)\n\tat org.example.factory.AppiumDriverFactory.<clinit>(AppiumDriverFactory.java:30)\n\t... 19 more\nCaused by: java.net.ConnectException: Connection refused (Connection refused)\n\tat java.base/java.net.PlainSocketImpl.socketConnect(Native Method)\n\tat java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)\n\tat java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)\n\tat java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)\n\tat java.base/java.net.Socket.connect(Socket.java:608)\n\tat java.base/java.net.Socket.connect(Socket.java:557)\n\tat java.base/java.net.Socket.<init>(Socket.java:453)\n\tat java.base/java.net.Socket.<init>(Socket.java:230)\n\tat se.vidstige.jadb.JadbConnection.createTransport(JadbConnection.java:27)\n\tat se.vidstige.jadb.JadbConnection.getDevices(JadbConnection.java:60)\n\tat org.example.factory.AppiumDriverFactory.getDevices(AppiumDriverFactory.java:57)\n\t... 20 more\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1678954947148,"stop":1678954947160}],"afters":[{"name":"tearDownTest","status":"broken","stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1678954952362,"stop":1678954952362}],"links":[],"start":1678954947131,"stop":1678954952362}